version: "3.4"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todo-list
    ports:
      - 3306:3306
    expose:
      - "3306"
    restart: always
    networks:
      - shared-networks
  server:
    build: ./server
    container_name: server_container
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - shared-networks
  client:
    build: ./client
    container_name: client_container
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

networks:
  shared-networks:
